// <auto-generated />
using System;
using AccountServices.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountService.Infra.Data.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20190801114053_Account")]
    partial class Account
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountServices.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Blocked");

                    b.Property<string>("HolderAccountName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<double>("ValueBalance");

                    b.Property<double>("ValueLimit");

                    b.HasKey("Guid")
                        .HasName("Guid");

                    b.ToTable("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
